// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSelect = require("react-select");

function make(options, children) {
  return ReasonReact.wrapJsForReason(ReactSelect.default, {
              options: options
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
